// ensure-gryphon.js — make `npm run build` work in a clean checkout OR a
// source archive with no git metadata.
//
// Athena's bundle imports Gryphon SOURCE from vendor/gryphon/ (see build.js),
// so a build needs that tree present. Two ways it can be missing:
//
//   1. A bare `git clone` leaves the submodule empty. Recoverable with
//      `git submodule update` — this was the 1.7.6 fix.
//   2. A SOURCE ARCHIVE (tarball/zip) has no .git at all, so there is no
//      submodule to update and no recorded pin to read. The Obsidian plugin
//      review builds this way; step 1 fails there with
//      "fatal: not a git repository" and the build stops.
//
// For (2) the commit is read from vendor/gryphon.pin — a plain file mirroring
// the submodule pin, generated by scripts/sync-gryphon-pin.js — and the tree
// is fetched from GitHub's codeload endpoint. Fetching BY COMMIT SHA means the
// bytes are pinned exactly as the submodule pins them; a moved tag or branch
// cannot change what a given release builds against.
//
// No-op when the submodule is already populated, so CI (`submodules:
// recursive`) and `build:all` are unaffected. Runs as the first step of
// `build` so it fires on a plain `npm run build` even with --ignore-scripts.
const fs = require("fs");
const path = require("path");
const os = require("os");
const { execSync } = require("child_process");

const SENTINEL = "vendor/gryphon/src/chat-view.js"; // a source file Athena imports
const VENDOR_DIR = "vendor/gryphon";
const VENDOR_NODE_MODULES = "vendor/gryphon/node_modules";
const PIN_FILE = "vendor/gryphon.pin";
const REPO = "polleoai/gryphon";

// Commands below interpolate only values validated as 40-char hex or built
// from fixed literals — no user input reaches a shell. (build.js uses
// execSync the same way.)
function sh(cmd) {
  execSync(cmd, { stdio: "inherit" });
}

function readPin() {
  if (!fs.existsSync(PIN_FILE)) return null;
  const raw = fs.readFileSync(PIN_FILE, "utf8").trim();
  // Validate before it reaches a URL or a filesystem path.
  return /^[0-9a-f]{40}$/.test(raw) ? raw : null;
}

async function fetchTarball(sha) {
  const url = `https://codeload.github.com/${REPO}/tar.gz/${sha}`;
  console.log(`[ensure-gryphon] fetching Gryphon ${sha.slice(0, 12)} from codeload…`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
  const tmp = path.join(os.tmpdir(), `gryphon-${sha.slice(0, 12)}.tar.gz`);
  fs.writeFileSync(tmp, Buffer.from(await res.arrayBuffer()));
  fs.mkdirSync(VENDOR_DIR, { recursive: true });
  // --strip-components=1 drops the <repo>-<sha>/ wrapper the archive adds.
  sh(`tar -xzf "${tmp}" -C "${VENDOR_DIR}" --strip-components=1`);
  fs.unlinkSync(tmp);
}

async function main() {
  if (!fs.existsSync(SENTINEL)) {
    console.log("[ensure-gryphon] vendor/gryphon is empty — initializing submodule…");
    try {
      sh("git submodule update --init --recursive vendor/gryphon");
    } catch {
      // No .git (source archive) or no network for the submodule — fall
      // through to the pinned-tarball path below.
    }
  }

  if (!fs.existsSync(SENTINEL)) {
    const pin = readPin();
    if (!pin) {
      console.error(
        `\n[ensure-gryphon] vendor/gryphon is missing and ${PIN_FILE} is absent or malformed.\n` +
        `  Athena bundles Gryphon's source from this submodule. Clone with git:\n` +
        `    git clone --recurse-submodules https://github.com/${REPO.split("/")[0]}/athena\n`
      );
      process.exit(1);
    }
    try {
      await fetchTarball(pin);
    } catch (err) {
      console.error(
        `\n[ensure-gryphon] could not fetch Gryphon ${pin.slice(0, 12)}: ${err.message}\n` +
        `  A build from a source archive downloads Gryphon instead of using git,\n` +
        `  so it needs network access. With git available, clone instead:\n` +
        `    git clone --recurse-submodules https://github.com/${REPO.split("/")[0]}/athena\n`
      );
      process.exit(1);
    }
  }

  if (!fs.existsSync(SENTINEL)) {
    console.error(
      `\n[ensure-gryphon] vendor/gryphon still has no ${SENTINEL} after fetching.\n` +
      `  The pinned commit may not contain the expected layout.\n`
    );
    process.exit(1);
  }

  if (!fs.existsSync(VENDOR_NODE_MODULES)) {
    // `npm ci` when the vendored lockfile is present, matching what release
    // CI runs (`cd vendor/gryphon && npm ci`). `npm install` may resolve a
    // newer in-range version than the lockfile pins, and those dependencies
    // are bundled into main.js — so the same commit could produce different
    // bytes depending on when and where it was built, which is exactly the
    // "build output does not match the released artifact" finding. Fall back
    // to install only when there is no lockfile to honour.
    const hasLock = fs.existsSync(path.join(VENDOR_DIR, "package-lock.json"));
    const verb = hasLock ? "ci" : "install";
    console.log(`[ensure-gryphon] installing vendor/gryphon dependencies (npm ${verb})…`);
    sh(`npm --prefix ${VENDOR_DIR} ${verb} --no-audit --no-fund --silent`);
  }
}

main().catch((err) => {
  console.error(`[ensure-gryphon] unexpected failure: ${err.stack || err}`);
  process.exit(1);
});
